### ISSUE TITLE
is there any example

### ISSUE THREAD

**Issue by quantrpeter** [cuhk-eda/CULS#1]
hi
   is there any example to use this tool?
thanks

**Comment by tefantasy** [comment]
Hi,

Could you please follow the instructions in Building and Getting Started sections in README.md? If there is anything unclear, please feel free to let me know.

**Comment by quantrpeter** [comment]
thanks, are you currently a student from CUHK?

**Comment by tefantasy** [comment]
If you want to contact the maintainers, please check the Authors section in README.md.

**Comment by tefantasy** [comment]
If you have further questions, please open a new issue.
