### ISSUE TITLE
generating .aig file 

### ISSUE THREAD

**Issue by jinz2014** [cuhk-eda/CULS#3]
Could you please provide instructions of generating .aig files for larger problem sizes ?

Currently, ../abc/i10.aig is available.

Thanks

**Comment by tefantasy** [comment]
If you want to write your own .aig file, you may refer to the [aig format spec](https://fmv.jku.at/aiger/FORMAT-20070427.pdf).

Or, if you just want to have more AIG networks to play around with our tool, you may check out the [EPFL benchmarks](https://github.com/lsils/benchmarks).
