### ISSUE TITLE
Considering Level Change During Rewrite

### ISSUE THREAD

**Issue by Polarisjame** [cuhk-eda/CULS#4]
I recently noticed that the gpu src code doesn't consider level increasing during Evaluating the Subgraph, related(rewrite.cu:429):
```c
  if (saved - nodesAdded < 0 || (saved - nodesAdded == 0 && !fUseZeros)) // Subgraph with higher level will be considered in this scope
                continue;
  if (saved - nodesAdded < reduction || (saved - nodesAdded == reduction && rtLevel >= bestLevel))
                continue;
```
I'm considering to use `savedLevel = nodeLevels[id]` with condition control:`!fUpdateLevel && savedLevel - rtLevel < 0` to avoid level increasing, is that right?

**Comment by tefantasy** [comment]
It makes sense to me, but I would also anticipate that adding the level constraint will lead to less number of feasible structures and a degradation in area.

**Comment by Polarisjame** [comment]
> It makes sense to me, but I would also anticipate that adding the level constraint will lead to less number of feasible structures and a degradation in area.

Thanks for your reply,  it's true that consider evel constraint will result in area degradation, I'm trying to expand the explore space and doubling or tripling the algorithm in-place to mitigate the decline
