### ISSUE TITLE
Refactor Failed 

### ISSUE THREAD

**Issue by Polarisjame** [cuhk-eda/CULS#5]
Error:
```c++
/src/algorithms/refactor.cu:619: void unbindAllKeys(const unsigned long long *, const unsigned int *, int *, int *, int, int, int): block: [0,0,0], thread: [0,0,0] Assertion `*(vReconstructedIds - 1) < nObjs` failed.
*(vReconstructedIds-1): 11528, nObjs: 11487
```
To reproduce the issue:
`./abcg -c "gread ../data/aig_random_control/voter.aig; gtime; grf -K 12; gtime; gps; grf; gtime; gps; grf; gtime; gps; grf; gtime; gps; grf; gtime; gps; gwrite ./test.aig"`

**Comment by tefantasy** [comment]
Hi, please always use `rf -m` for refactoring, which is the algorithm described in our paper. The `rf` implementation is deprecated and no longer supported.

**Comment by tefantasy** [comment]
If there is any problem with the new refactoring implementation, feel free to open a new issue.
